video.getBarData = function() {
    var barDataSet = [{
        name: '阿拉善',
        offline: '800',
        online: '2000',
    }, {
        name: '乌海',
        offline: '900',
        online: '3000',
    }, {
        name: '鄂尔多斯',
        offline: '850',
        online: '2500',
    }, {
        name: '巴彦淖尔',
        offline: '800',
        online: '1800',
    }, {
        name: '包头',
        offline: '1200',
        online: '3300',
    }, {
        name: '呼和浩特',
        offline: '800',
        online: '1800',
    }, {
        name: '乌兰察布',
        offline: '1300',
        online: '3600',
    }, {
        name: '锡林郭勒',
        offline: '800',
        online: '2000',
    }, {
        name: '赤峰',
        offline: '800',
        online: '2000',
    }, {
        name: '通辽',
        offline: '800',
        online: '2000',
    }, {
        name: '兴安',
        offline: '1500',
        online: '2000',
    }, {
        name: '呼伦贝尔',
        offline: '800',
        online: '2000',
    }]
    return barDataSet;
}
